#pragma once

#define SPINNER_RAINBOWMIX
#define SPINNER_ROTATINGHEART
#define SPINNER_ANG8
#define SPINNER_CLOCK
#define SPINNER_PULSAR
#define SPINNER_DOTSTOBAR
#define SPINNER_ATOM
#define SPINNER_BARCHARTRAINBOW
#define SPINNER_SWINGDOTS
